"""
Application settings loaded from environment variables.
Uses pydantic-settings for validation and type casting.

Compared to escalasPT this adds:
  - TEST_DATABASE_URL, validated to be a dedicated `_test` database, so
    running pytest can never drop the development database.
  - Separate encryption keys per purpose (attachments, free-text fields,
    identification fields, identification search index).
"""

from __future__ import annotations

import base64
import json
import sys
from functools import lru_cache
from typing import List

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

_INSECURE_SECRETS = {"CHANGE-ME-IN-PRODUCTION", "GENERATE_ME", "", "secret", "changeme"}


def _is_fernet_key(value: str) -> bool:
    try:
        return len(base64.urlsafe_b64decode(value + "==")) == 32
    except Exception:
        return False


class Settings(BaseSettings):
    """Central configuration — every value has a sensible default for local dev."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ── App ───────────────────────────────────────────────────
    APP_NAME: str = "Caderno de Serviço"
    APP_ENV: str = "production"
    APP_DEBUG: bool = False
    LOG_LEVEL: str = "INFO"

    # ── Database ──────────────────────────────────────────────
    # The application connects as the LIMITED role (caderno_app), never as the
    # table owner — that is what makes the audit_logs REVOKE and RLS effective.
    DATABASE_URL: str = "postgresql+asyncpg://caderno_app:pass@localhost:5432/caderno"
    TEST_DATABASE_URL: str = "postgresql+asyncpg://caderno_app:pass@localhost:5432/caderno_test"

    # ── Redis ─────────────────────────────────────────────────
    REDIS_URL: str = "redis://:pass@localhost:6379/0"

    # ── JWT ───────────────────────────────────────────────────
    JWT_SECRET_KEY: str = "CHANGE-ME-IN-PRODUCTION"
    JWT_ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 15
    REFRESH_TOKEN_EXPIRE_DAYS: int = 30  # field work: long shifts, bad signal

    # ── TOTP ──────────────────────────────────────────────────
    TOTP_ISSUER_NAME: str = "Caderno de Serviço"
    TOTP_ENCRYPTION_KEY: str = ""

    # ── Encryption (phases 1+; generated by deploy/setup.sh from day one) ──
    FIELD_ENCRYPTION_KEY: str = ""      # registos.descricao / resultado
    ATTACHMENT_MASTER_KEY: str = ""     # wraps per-file attachment keys
    IDENT_FIELD_KEY: str = ""           # identification module fields
    IDENT_INDEX_KEY: str = ""           # HMAC key for exact-match lookups

    # ── Account Lockout ───────────────────────────────────────
    ACCOUNT_LOCKOUT_ATTEMPTS: int = 5
    ACCOUNT_LOCKOUT_MINUTES: int = 15
    MAX_CONCURRENT_SESSIONS: int = 3

    # ── CORS ──────────────────────────────────────────────────
    # Same-origin in production (nginx serves the SPA and proxies /api),
    # so this only matters for `npm run dev`.
    CORS_ORIGINS: str = '["http://localhost:5173"]'

    @property
    def cors_origins_list(self) -> List[str]:
        return json.loads(self.CORS_ORIGINS)

    # ── Rate Limiting ─────────────────────────────────────────
    RATE_LIMIT_LOGIN: str = "5/minute"
    RATE_LIMIT_DEFAULT: str = "120/minute"

    # ── Validators ────────────────────────────────────────────

    @field_validator("CORS_ORIGINS")
    @classmethod
    def validate_cors_origins(cls, v: str, info) -> str:
        env = info.data.get("APP_ENV", "production")
        origins = json.loads(v) if v else []
        if env != "development":
            unsafe = [o for o in origins if "localhost" in o or "127.0.0.1" in o]
            if unsafe:
                safe = [o for o in origins if o not in unsafe]
                print(
                    f"WARNING: CORS_ORIGINS contained localhost entries in {env} mode: "
                    f"{unsafe}. They have been removed automatically.",
                    file=sys.stderr,
                )
                return json.dumps(safe)
        return v

    @field_validator("JWT_SECRET_KEY")
    @classmethod
    def validate_jwt_secret(cls, v: str, info) -> str:
        env = info.data.get("APP_ENV", "development")
        if env != "development" and v in _INSECURE_SECRETS:
            print(
                "FATAL: JWT_SECRET_KEY is an insecure default. "
                "Generate one with: openssl rand -hex 32",
                file=sys.stderr,
            )
            sys.exit(1)
        if env == "development" and v in _INSECURE_SECRETS:
            import warnings

            warnings.warn("JWT_SECRET_KEY is insecure — fine for dev, fatal in prod.", stacklevel=2)
        return v

    @field_validator("TEST_DATABASE_URL")
    @classmethod
    def validate_test_database(cls, v: str) -> str:
        """
        The test suite creates and drops every table. escalasPT points it at
        DATABASE_URL, so `pytest` with a dev .env wipes the dev database.
        Refuse anything that is not clearly a dedicated test database.
        """
        db_name = v.rsplit("/", 1)[-1].split("?")[0]
        if not db_name.endswith("_test"):
            raise ValueError(
                f"TEST_DATABASE_URL must point at a dedicated database whose name "
                f"ends in '_test' (got '{db_name}'). The test suite drops every table."
            )
        return v

    @field_validator(
        "TOTP_ENCRYPTION_KEY",
        "FIELD_ENCRYPTION_KEY",
        "ATTACHMENT_MASTER_KEY",
        "IDENT_FIELD_KEY",
        "IDENT_INDEX_KEY",
    )
    @classmethod
    def validate_optional_fernet_key(cls, v: str, info) -> str:
        if v == "":
            return v  # feature not enabled yet
        if v in _INSECURE_SECRETS or not _is_fernet_key(v):
            raise ValueError(
                f"{info.field_name} must be a 32-byte urlsafe-base64 key (generate with: "
                "python -c \"from cryptography.fernet import Fernet; "
                "print(Fernet.generate_key().decode())\")"
            )
        return v


@lru_cache
def get_settings() -> Settings:
    """Cached settings singleton."""
    return Settings()
