[versions]
spring-boot = "4.1.1"
spring-modulith = "2.1.1"
springdoc = "3.1.1"
openpdf = "3.0.5"
bouncycastle = "1.86"
pdfbox = "3.0.8"

[libraries]
spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "spring-modulith" }
springdoc-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "springdoc" }
openpdf = { module = "com.github.librepdf:openpdf", version.ref = "openpdf" }
bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
